// <auto-generated />
using System;
using AzubiVerwaltungBackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzubiverwaltungBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413141026_ReworkZuweisung")]
    partial class ReworkZuweisung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzubiVerwaltungBackEnd.Models.Azubi", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("AdminRights")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordhash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Azubis", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AdminRights = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rgrubendorfer@hansalog.de",
                            FirstName = "Robin",
                            LastName = "Grubendorfer",
                            passwordhash = "$2a$11$8zvOyuIaoqUrs5/RB.5oXOgv35fTm7HVuuA6GvUV4MfAs3V8qZcMC"
                        });
                });

            modelBuilder.Entity("AzubiVerwaltungBackEnd.Models.Dienst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intervall")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Wochentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dienste", (string)null);
                });

            modelBuilder.Entity("AzubiVerwaltungBackEnd.Models.Zuweisung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AzubiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("DienstId")
                        .HasColumnType("int");

                    b.Property<bool>("IstFeiertag")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AzubiId");

                    b.HasIndex("DienstId");

                    b.ToTable("Zuweisung", (string)null);
                });

            modelBuilder.Entity("AzubiVerwaltungBackEnd.Models.Zuweisung", b =>
                {
                    b.HasOne("AzubiVerwaltungBackEnd.Models.Azubi", "Azubi")
                        .WithMany()
                        .HasForeignKey("AzubiId");

                    b.HasOne("AzubiVerwaltungBackEnd.Models.Dienst", "Dienst")
                        .WithMany()
                        .HasForeignKey("DienstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Azubi");

                    b.Navigation("Dienst");
                });
#pragma warning restore 612, 618
        }
    }
}
